name: PyPI Release

# on:
#   push:
on:
   workflow_dispatch:
    tags:
      - "*"

jobs:
  release-using-twine:
    name: Build and publish to PyPI UUsing Twine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build the dist files
        run: python setup.py sdist bdist_wheel
      - name: Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/* 
        -- skip-existing

      # package if exists exit ... Get input as version and publish